### ISSUE TITLE
Move unit tests out of parser.rs when possible

### ISSUE THREAD

**Issue by fitzgen** [fitzgen/gimli#18]
A lot of the unit tests in parser.rs are testing non-public helper parser functions, so they can't move out or they would lose access to the non-public parser functions. However, for the tests that are only using public APIs, we should move them out to `tests/some_test.rs`.

**Comment by philipc** [comment]
My understanding is that the top level `tests` is intended for integration tests, while unit tests should be kept in sub modules of the module they are testing. The rust docs seem to agree with this. So your change here isn't what I would expect.

So I would like to move the tests to a submodule, if that's ok. It will make it easier to browse the code; currently I'm finding it difficult to read and navigate due to the tests interspersed with the code.  Alternatively, I'm open to suggestions for how to navigate better (I use vim).

**Comment by fitzgen** [comment]
> So I would like to move the tests to a submodule, if that's ok.

Yes, this sounds great. We should probably move the tests I moved to `./tests/foo.rs` to `./src/test.rs`.

> It will make it easier to browse the code; currently I'm finding it difficult to read and navigate due to the tests interspersed with the code.

Unfortunately, many of the unit tests are testing private functions, which means that they do need to be in the same module as the function they're testing. So I'm not sure what to do with these tests. We could move them to the bottom of the file, if you think that it is easier to separate tests and "real" code. Right now the tests are near the things they are testing. Not clear which is better to me.

I use racer with emacs, and everything I hear is that racer works well with vim too. It provides a "jump to the definition of this type/function/variable" command that I use frequently. Do you have racer set up?

Finally, I think we could split `parser.rs` into multiple files. At the very least, the abbreviation parsing seems completely uncoupled from DIE parsing, and could be split out into `abbrevs.rs`.
