### ISSUE TITLE
meaning of 'code' field in DebuggingInformationEntry is unclear

### ISSUE THREAD

**Issue by jvns** [fitzgen/gimli#35]
I was comparing the output of `dwarfdump` to the output of the dwarfdump example program. Most things match up (if I convert hex numbers to little endian byte arrays)! Hooray!

However! One thing that did not match is the numbers `<0x18ee>`  and `<41>` (in the output I pasted below)

This number 0x18ee in the `dwarfdump` output comes from `dwarf_die_CU_offset` in libdwarf. `41` comes from the `code` field in DebuggingInformationEntry. These two numbers obviously mean different things. But what does `code` mean? And how can I get the number I want?

here are the two things I'm looking at:

```
$ dwarfdump $ruby_file
< 1><0x000018ee>    DW_TAG_structure_type
                      DW_AT_name                  "rb_thread_struct"
                      DW_AT_byte_size             0x000003e8
                      DW_AT_decl_file             0x00000002 /home/bork/Downloads/ruby-2.1.6/vm_core.h
                      DW_AT_decl_line             0x0000020c
                      DW_AT_sibling               <0x00001c9a>
```

```
$ ./examples/dwarfdump $ruby_file
        <41> <DW_TAG_structure_type>
            DW_AT_name = "rb_thread_struct"
            DW_AT_byte_size = Data([232, 3])
            DW_AT_decl_file = Data([2])
            DW_AT_decl_line = Data([12, 2])
            DW_AT_sibling = UnitRef(UnitOffset(7322))

```

**Comment by fitzgen** [comment]
See also #15, I whipped up the mini-clone of dwarfdump pretty quick and it would be really nice if we matched the real format exactly. This is just one of the ways we don't match up.

The way that DWARF encodes entries and their attributes is pretty cool. Rather than repeating the metadata every time the entry is serialized, its set of attributes and their types are formalized in an abbreviation in the `.debug_abbrev` section. Then, each entry just says which attributes it is using via its abbreviation code. This ends up making the serialization a lot more compact. So the `code` here is the entry's abbreviation code. I believe that `dwarfdump` doesn't output this code.

That number that you're seeing in the canonical `dwarfdump` and `examples/dwarfdump.rs` is missing is the offset into the section (or maybe the compilation unit? I think the section, though) at which the entry is located. We don't have this super accessible at the moment, but it is certainly do-able. Do you need it for some reason? Can I ask why?

**Comment by philipc** [comment]
If we want to match dwarfdump output then I think we'll need to add `offset` members to units and entries (or at least the cursor).

**Comment by jvns** [comment]
so -- when we print out the `DW_AT_type` of an object, like `DW_AT_type = UnitRef(UnitOffset(1401))`, I think it's an offset into the section and not the abbreviation code?

Basically I want to go from the DW_AT_type to the DIE that the type is referencing.

**Comment by fitzgen** [comment]
> so -- when we print out the DW_AT_type of an object, like DW_AT_type = UnitRef(UnitOffset(1401)), I think it's an offset into the section and not the abbreviation code?

Attributes of the form `DW_FORM_ref*`, which is what `UnitRef` and `UnitOffset` correspond to, is an offset into the current compilation unit, not the section (there are potentially multiple units per section). We could probably better document this stuff...

See 7.5.4, page 149 of the standard:

> The first type of reference can identify any debugging information entry within the
containing unit. This type of reference is an offset from the first byte of the compilation
header for the compilation unit containing the reference. There are five forms for this type of
reference. There are fixed length forms for one, two, four and eight byte offsets (respectively,
DW_FORM_ref1, DW_FORM_ref2, DW_FORM_ref4, and DW_FORM_ref8). There is
also an unsigned variable length offset encoded form that uses unsigned LEB128 numbers
(DW_FORM_ref_udata). Because this type of reference is within the containing compilation
unit no relocation of the value is required.

This is why we try (or, are trying) to define newtypes for all the various offsets -- there's so many types of indices and things to index into and it is so easy to mix them up!

> Basically I want to go from the DW_AT_type to the DIE that the type is referencing.

We do this for following `DW_AT_sibling` ptrs in `next_sibling` right now: https://github.com/fitzgen/gimli/blob/master/src/parser.rs#L2433

Seems like we need to expose this as a method to jump the cursor to a given offset.

**Comment by jvns** [comment]
That sounds reasonable!

one other question (I should probably just read the standard)

In my file, these 4 entries have the same abbreviation code, despite there being no obvious-to-me similarities between them. is that expected? They're all members of the same struct.

```
                <8> <DW_TAG_member>
                    DW_AT_name = "_flags2"
                    DW_AT_decl_file = Data([4])
                    DW_AT_decl_line = Data([44, 1])
                    DW_AT_type = UnitRef(UnitOffset(106))
                    DW_AT_data_member_location = Block([35, 116])
                <8> <DW_TAG_member>
                    DW_AT_name = "_old_offset"
                    DW_AT_decl_file = Data([4])
                    DW_AT_decl_line = Data([46, 1])
                    DW_AT_type = UnitRef(UnitOffset(120))
                    DW_AT_data_member_location = Block([35, 120])
                <8> <DW_TAG_member>
                    DW_AT_name = "_cur_column"
                    DW_AT_decl_file = Data([4])
                    DW_AT_decl_line = Data([50, 1])
                    DW_AT_type = UnitRef(UnitOffset(78))
                    DW_AT_data_member_location = Block([35, 128, 1])
                <8> <DW_TAG_member>
                    DW_AT_name = "_vtable_offset"
                    DW_AT_decl_file = Data([4])
                    DW_AT_decl_line = Data([51, 1])
                    DW_AT_type = UnitRef(UnitOffset(92))
                    DW_AT_data_member_location = Block([35, 130, 1])

```

**Comment by philipc** [comment]
Those entries all use the same abbreviation code because they all have the same attribute types (both name and form), only the values of the attributes differ, so their abbreviations are identical and can be shared. It doesn't imply any other commonality between the entries.

In general, I don't think a consumer of this API will need to use the abbreviation code. It's only an artefact of how the entry is encoded. This is probably why dwarfdump doesn't display it.

**Comment by fitzgen** [comment]
The standard is pretty easy to read overall (easier than ECMAScript or many web standards IMO), but it is indeed pretty huge. I would never discourage anyone from going to first principles!

> In my file, these 4 entries have the same abbreviation code, despite there being no obvious-to-me similarities between them. is that expected? They're all members of the same struct.

Yes, this is expected. Despite referring to different members of the struct, they all have the same five attributes, which each have the same form:

* `DW_AT_name` is a `DW_FORM_str_ref`
* `DW_AT_decl_file` is a `DW_FORM_data1`
* `DW_AT_decl_line` is a `DW_FORM_data2`
* `DW_AT_type` is a `DW_FORM_ref*` of some sort
* `DW_AT_data_member_location` is `DW_FORM_block*` of some sort

**Comment by fitzgen** [comment]
> In general, I don't think a consumer of this API will need to use the abbreviation code. It's only an artefact of how the entry is encoded. This is probably why dwarfdump doesn't display it.

Yeah, I think we could probably stop exposing it, by my inner hoarder is like "but WHAT IF?"

**Comment by fitzgen** [comment]
@jvns: You can think of this abbreviation scheme vs JSON kind of like how a C compiler just knows what offset each member is at vs how python stores an object's members in a dictionary internally and has to repeat each member name in memory as keys in that dictionary. Hope that analogy helps..

**Comment by fitzgen** [comment]
Fixed in https://github.com/fitzgen/gimli/commit/3565ff2d88cf3521fc35c2621c6fae918071561a
